### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by bonndan** [fghaas/froscon2016#1]
Hi Florian,

thanks for the interesting talk at FrOsCon. I could not find your email address anywhere so I misuse github. Feel free to delete this issue and answer by email. My two cents:

You mainly criticized formal Scrum and you're probably right about all or most of your points (few days earlier I came to find http://okigiveup.net/not-big-fan-of-scrum/ ). However, as you and some spectators pointed out, hardly anybody uses formal Scrum which leaves me with the impression of a more or less theoretical discourse.

What I've been missing are a few more hints on how to do it better. How exactly do you and your team do "Scrum" (or however it may be called then)? Sharing your real life improvements would have added some more value to the talk.

Thanks and best regards

Daniel

**Comment by fghaas** [comment]
My email address is simply `<firstname>@hastexo.com`, but I appreciate having the discussion here. :)

"Hardly anybody uses formal Scrum" is a bit of an issue, as Scrum itself _expressly_ says whatever you do that's partly Scrum _isn't Scrum._ So what you end up with is that _nobody_ is actually using Scrum by its own, rigid definition — which renders the method useless, don't you think?

Our team emphatically doesn't use Scrum. There are a few things where our development method is inspired by Scrum, and I've tried to point this out in the talk, but to summarize:
- Product backlog: We use that, practically unchanged from Scrum.
- Sprints: We do define those, but (1) sprints aren't followed immediately by the next sprint (it's normal and fine for a project to be on hiatus for a week or two while people work on something else), (2) sprints are planned in advance, under the pretext that all sprints except the current one are _tentative_ in their planning.
- Story points: not used the Scrum way. We don't use planning poker or some other silliness to guess overall complexity by consensus; we break user stories in to tasks that can be completed and estimated by one person, and then we add the estimates for those tasks up to come up with an complexity of the user story.

Does that explain things a bit better?

**Comment by bonndan** [comment]
I got your your point regarding the definition and mostly agree with it, but in the end we're talking about a rigid definition here and not exactly the method or the idea behind it. If these were useless you would probably switch to Kanban, waterfall or XYZ. Maybe it is just time for the next management hype to enlighten us all.

What about the meeting overkill (apart from dailies)? Do you practise all steps in exact order and amount?

**Comment by fghaas** [comment]
Good grief, no. :) We have _one_ weekly meeting that everyone is expected to participate in by video conference. Everything else is asynchronous, through a Slack channel that is integrated with GitHub and Taiga.

**Comment by bonndan** [comment]
:+1: 

Thanks a lot for your answers!

**Comment by fghaas** [comment]
Quite welcome — my pleasure!
